"""Rendering: terminal for the author, markdown for everyone else."""

from __future__ import annotations

from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

from .diagram import data_summary, legend, render
from .engine import Severity, Summary, Threat
from .model import Model
from .stride import Stride

SEVERITY_STYLE = {
    Severity.CRITICAL: "bright_red",
    Severity.HIGH: "red",
    Severity.MEDIUM: "yellow",
    Severity.LOW: "green",
}


def render_terminal(
    model: Model, threats: list[Threat], summary: Summary, console: Console, limit: int = 12
) -> None:
    stats = model.stats()
    header = Text()
    header.append(f"{model.name}", style="bold")
    header.append(f"  v{model.version}\n", style="dim")
    header.append(
        f"{stats['process']} processes · {stats['store']} stores · "
        f"{stats['external']} external · {stats['flow']} flows "
        f"({stats['crossing_flows']} cross a boundary)\n",
        style="dim",
    )
    header.append("inherent risk  ", style="dim")
    header.append(f"{summary.inherent_total}", style="bold")
    header.append("   residual  ", style="dim")
    header.append(f"{summary.residual_total}", style="bold")
    header.append(f"   ({summary.risk_reduction:.0%} reduced by declared controls)", style="dim")
    console.print(Panel(header, title="threat model", border_style="blue", expand=False))

    counts = Table.grid(padding=(0, 3))
    counts.add_row(
        *[
            Text(f"{summary.by_severity[s]} {s.value}", style=SEVERITY_STYLE[s])
            for s in (Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW)
        ],
        Text(f"{summary.accepted} accepted", style="dim"),
    )
    console.print(counts)
    console.print()

    table = Table(
        title=f"Top threats by residual risk ({summary.open} open of {summary.total})",
        title_style="bold",
        header_style="dim",
    )
    table.add_column("id", style="bold")
    table.add_column("category", style="magenta")
    table.add_column("subject", style="cyan")
    table.add_column("I→R", justify="center")
    table.add_column("sev")
    table.add_column("threat / next control", overflow="fold")

    shown = [t for t in threats if not t.accepted][:limit]
    for threat in shown:
        arrow = f"{threat.inherent_risk}→{threat.residual_risk}"
        detail = Text(threat.rule.title)
        if threat.missing_controls:
            detail.append(f"\nadd: {threat.missing_controls[0]}", style="dim")
        elif threat.applied_controls:
            detail.append(f"\nmitigated by: {', '.join(threat.applied_controls)}", style="dim")
        table.add_row(
            threat.rule.id,
            threat.category.label,
            threat.subject_id,
            arrow,
            Text(threat.severity.value, style=SEVERITY_STYLE[threat.severity]),
            detail,
        )
    console.print(table)

    accepted = [t for t in threats if t.accepted]
    if accepted:
        console.print()
        table = Table(title="Accepted risks", title_style="bold", header_style="dim")
        table.add_column("id", style="bold")
        table.add_column("subject", style="cyan")
        table.add_column("reason", overflow="fold", style="dim")
        for threat in accepted:
            table.add_row(threat.rule.id, threat.subject_id, threat.accepted_reason or "")
        console.print(table)


def render_markdown(
    model: Model, threats: list[Threat], summary: Summary, *, with_diagram: bool = True
) -> str:
    lines = [
        f"# Threat model — {model.name}",
        "",
        f"Version {model.version}"
        + (f" · owned by {model.owner}" if model.owner else "")
        + " · generated by `tmac`",
        "",
        model.description,
        "",
        "## Summary",
        "",
        "| | |",
        "| --- | --- |",
        f"| Threats enumerated | {summary.total} |",
        f"| Open (above low) | **{summary.open}** |",
        f"| Accepted with a recorded reason | {summary.accepted} |",
        f"| Inherent risk | {summary.inherent_total} |",
        f"| Residual risk | **{summary.residual_total}** |",
        f"| Reduction from declared controls | {summary.risk_reduction:.0%} |",
        "",
        "| Severity | Open |",
        "| --- | ---: |",
    ]
    for severity in (Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW):
        lines.append(f"| {severity.value.title()} | {summary.by_severity[severity]} |")

    lines += ["", "| STRIDE category | Threats | Violates |", "| --- | ---: | --- |"]
    for category in Stride:
        lines.append(
            f"| {category.label} | {summary.by_category[category]} | {category.violates} |"
        )

    if with_diagram:
        lines += [
            "",
            "## Data-flow diagram",
            "",
            "```mermaid",
            render(model, threats, show_risk=True),
            "```",
            "",
            legend(),
            "",
            "## Where the data lives",
            "",
            data_summary(model),
        ]

    lines += ["", "## Threats", ""]
    for severity in (Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW):
        batch = [t for t in threats if t.severity is severity and not t.accepted]
        if not batch:
            continue
        lines += [f"### {severity.value.title()} ({len(batch)})", ""]
        for threat in batch:
            lines += [
                f"#### `{threat.rule.id}` {threat.rule.title}",
                "",
                f"- **Subject**: `{threat.subject_id}` — {threat.subject_name} "
                f"({threat.subject_kind.label})",
                f"- **Category**: {threat.category.label} (violates "
                f"{threat.category.violates})",
                f"- **Risk**: inherent {threat.inherent_risk} "
                f"(L{threat.likelihood}×I{threat.impact}) → residual "
                f"**{threat.residual_risk}** (L{threat.residual_likelihood}×"
                f"I{threat.residual_impact})",
                "",
                threat.rule.description,
                "",
            ]
            if threat.why:
                lines += ["**Why this score**", ""]
                lines += [f"- {reason}" for reason in threat.why]
                lines.append("")
            if threat.applied_controls:
                lines.append(
                    f"**Controls already declared**: "
                    f"{', '.join(f'`{c}`' for c in threat.applied_controls)}"
                )
            if threat.missing_controls:
                lines.append(
                    f"**Controls that would close it**: "
                    f"{', '.join(f'`{c}`' for c in threat.missing_controls)}"
                )
            if threat.rule.references:
                lines.append(f"**References**: {', '.join(threat.rule.references)}")
            lines.append("")

    accepted = [t for t in threats if t.accepted]
    if accepted:
        lines += [
            "## Accepted risks",
            "",
            "Recorded decisions, not omissions. Each carries a reason because the "
            "loader refuses an acceptance without one.",
            "",
            "| Threat | Subject | Residual | Reason |",
            "| --- | --- | ---: | --- |",
        ]
        for threat in accepted:
            reason = " ".join((threat.accepted_reason or "").split())
            lines.append(
                f"| `{threat.rule.id}` | `{threat.subject_id}` | {threat.residual_risk} "
                f"| {reason} |"
            )
        lines.append("")

    return "\n".join(lines)
